### ISSUE TITLE
Attendance Report - Missing attendance

### ISSUE THREAD

**Issue by alexmckenzie1** [NomisNostab/Topo#109]
We ran the Attendance report for the period 1st Jan 2021 to 15 Jul 2022 for the 1st Ivanhoe venturer unit.  File attached.

Issues
No attendance is shown for any events in 2021 despite checks via Terrain showing there is attendance.
The report contains events from other sections (e.g. Scouts)

[AttendanceVenturer_Unit (2).csv](https://github.com/NomisNostab/Topo/files/9124262/AttendanceVenturer_Unit.2.csv)

**Comment by NomisNostab** [comment]
Hi Alex
Looks like you have some data that I haven't allowed for.
Stop and start Topo, and do the Attendance report with the same values.
Stop Topo.
Go to the Topo folder and email me the nlog-Topo-all.log file.
***@***.***

**Comment by NomisNostab** [comment]
Hi Alex,
Looking at some of our earlier attendance I can see a similar pattern.
Looking into the data coming back from Terrain and also the view of the activity in Terrain I can see that earlier events are only showing Participation and Attendance and I am using Attendance, this might be from when they split Attendance and Participate.
Anyway I will also check Participation if Attendance is empty.

**Comment by alexmckenzie1** [comment]
Does that mean you don’t need the file you requested?  
What about the multiple sections appearing on the report (e.g. Scouts when Venturer section is selected)?
And I assume you will bundle this change into the next release?
You are doing great work!
cheers
Alex

**Comment by NomisNostab** [comment]
Hi Alex

Please send through the log file, I'll need it to try to work out why you
are getting multiple sections.

Thanks.

**Comment by alexmckenzie1** [comment]
hi Simon,
Files attached as requested.

[AttendanceVenturer_Unit (3).csv](https://github.com/NomisNostab/Topo/files/9128897/AttendanceVenturer_Unit.3.csv)
[nlog-Topo-all.log](https://github.com/NomisNostab/Topo/files/9128898/nlog-Topo-all.log)

**Comment by NomisNostab** [comment]
Hi Alex,
When you are using Topo it is pretending to be you using Terrain.
For the Programming page in Terrain, can you click on the funny Calendar + icon (its next to Today) so that the list of available calendars is shown.
Make sure there are no Other Units calendars selected. Don't worry about the My Group and Unit calendars as I set those already.
Got to Topo, login and try the report.
If that fixes the problem, I'll clear the Other Units calendars as well.
Simon.

**Comment by alexmckenzie1** [comment]
hi Simon,
I had a play and confirmed that it is pulling the data from any calendar items i have visible (e.g. scouts) in the report even if I specify venturers as the Unit Calendar on the report.  If i turn off those calendars then the report only shows the venturer activities.
cheers
Alex

**Comment by NomisNostab** [comment]
Hi Alex

Thanks for doing that.
I make the change to Topo to unselect those calendars.

Simon

**Comment by alexmckenzie1** [comment]
Thanks for sorting it out so quickly.  And i saw the report had graduated from a CSV as well with new colour schemes :)

**Comment by NomisNostab** [comment]
Hi Alex,
See if the release at https://github.com/NomisNostab/Topo/releases/tag/v1.27.54 fixes everything.

Simon

**Comment by alexmckenzie1** [comment]
hi Simon - tested and working as expected.  Thanks for that!
cheers
Alex

**Comment by alexmckenzie1** [comment]
Thanks Simon,

Sorry for the delayed response - away with the cubs this weekend.

Does that mean you don't need the file?  And I assume you will bundle this into the next release?

You are doing great work!

Cheers,
Alex
