### ISSUE TITLE
Milestone report is blank

### ISSUE THREAD

**Issue by NomisNostab** [NomisNostab/Topo#11]
The Milestone report is blank for some sections but not others

**Comment by marklim** [comment]
This is due to a serialization issue in the GetGroupLifeResultModel class where the Milestone status_updated may be null. Will fix and raise PR

**Comment by marklim** [comment]
No permissions to push, but happy for you to fix. Change is to make Milestone.status_updated a nullable DateTime type

**Comment by NomisNostab** [comment]
Thanks Mark,
Have added you as a contributor.
Could you send through a response with this condition so I can process it correctly?

**Comment by NomisNostab** [comment]
Hi Mark,
Can you check to see if the SIA report works or has a similar issue in the deserialization?
Thanks.

**Comment by marklim** [comment]
PR https://github.com/NomisNostab/Topo/pull/15 to fix this issue.
SIA report is also blank but not cause by a deserialization exception. This looks to be a different issue
