### ISSUE TITLE
Unit Leader appointments are not reflected in various generated lists

### ISSUE THREAD

**Issue by CrispyCamper** [NomisNostab/Topo#112]
#### Issue Description:

If a youth member is appointed as a Unit Leader, their appointment is not reflected in generated lists.

#### What happens:

The appointment field is left blank

#### What you expected to happen:

They should have "UL" marked against their name in the same way that Patrol Leaders and Assistant Patrol Leaders are.

#### Steps to reproduce:

1. Set a youth member in a Unit as a Unit Leader in Scouts | Terrain
2. Launch Topo.exe, go to http://localhost:5000/ and log in
3. Go to "Member Lists" select the Unit with an appointed Unit Leader (Note: the resulting list shows PLs, APLs, and members of the Unit Council, but not ULs
4. Click "Generate Patrol List", "Generate Member List", or "Generate Patrol Sheet", and open the resulting document/s
5. Note how the Unit Leader appointment is not shown against the member's name
6. This occurs with any of the lists given below
...

____
#### Affected Versions:

- Topo v1.27.54
#### Affected Lists:
- _Member Lists_ - Member List Page + generated Patrol Lists, Member Lists, & Patrol Sheets
- _Program Events_ - Generated Sign In Sheets
- _SIA Report_ - SIA Report Page
- _Logbook Report_ - Logbook Report Page
- _Additional Awards Report_ - Additional Awards Report Page

**Comment by NomisNostab** [comment]
Hi,
I cache the member list each time Topo is run to reduce the number of times I call Terrain to get members.
If you change a member role whilst Topo is running the change won't be reflected until Topo is restarted.
Can you stop and start Topo and see if the roles are reflected on the Member List Page?
Simon

**Comment by CrispyCamper** [comment]
Yeah, the Unit Leader has been assigned in Terrain for a couple of months now.
On top of that, when I was testing it so I could open this issue, I realised I was using an old version of Topo, so I completely uninstalled it and downloaded the latest version, so it's definitely not due to it being assigned while Topo's running.
Cheers.

**Comment by NomisNostab** [comment]
Ok,
Can I get you to stop and start Topo, show the member list page for your unit.
Stop Topo, and in the folder where run run Topo from can you send me the nlog-Topo-all.log file. You can attach to this issue.
This is a log of the info Topo gets from Terrain and I can try to see why the Unit leader is not showing.
Also let me know which member is the Unit Leader in question.
Simon

**Comment by NomisNostab** [comment]
You can PM me on Messenger and I can give you my email address if you prefer.

**Comment by CrispyCamper** [comment]
Awesome! Thanks so much for that.

Cheeky question. Would it be possible for you to put an appointment identifier next to leaders' names? I know Terrain doesn't support leaders, so just "SL" for Section Leader would work.
It would just help for picking them out of a list at a glance.

**Comment by NomisNostab** [comment]
I have added to the Patrol List.
Any other lists you had in mind?

**Comment by CrispyCamper** [comment]
I think the only other places that has spaces for Adult Leader appointments would be the actual Logbook Report landing page when "IncludeLeaders" is checked (ie localhost:5000/Logbook?includeLeaders=True, not the generated report itself), and the generated Sign In Sheets for programmed events.

Thanks so much.
I also have a few other suggestions/feature requests that I'd like to share (via separate issue tickets of course) if you don't mind.

**Comment by mkg71** [comment]
Simon,

Can I request a "refresh cache" option. ie rather than a restart, go pull
the data again.  Put a warning on it, prior to use - so people understand
what it means to Terrain - ie a full scrape of their data again -
additional system load etc.

Cheers
Mike

------------------------------------
Mike Groeneweg
Perth, Western Australia
https://plus.google.com/u/0/+MikeGroeneweg
Telegram:  https://telegram.me/MikeGroeneweg
