### ISSUE TITLE
Attendance Report - Event Status

### ISSUE THREAD

**Issue by alexmckenzie1** [NomisNostab/Topo#113]
Hi Simon,
Having used the attendance report to review the last 12 months of activities I have found a number of activities that were not finalised correctly (and therefore don't count in the stats).  It would be great if the attendance report could identify whether an activity is still in draft or if it has been finalised.
thanks Alex

**Comment by NomisNostab** [comment]
Hi Alex,
That shouldn't be too much trouble.
Would something like 
Unit Council 26/07/2022 (C) -- Concluded
Knot Games 27/07/2022 (P) -- Planned
work for the headings on the report.
I could also show on the page as well.

Simon

**Comment by alexmckenzie1** [comment]
hi Simon - my personal preference is to keep the data fields separate for sorting/filtering so I would add a new row like this if possible?

![image](https://user-images.githubusercontent.com/109391101/182221668-fe649a4f-1a11-4730-8d2e-e1cb30e41f2e.png)

Is this what you mean by show on page or are you suggesting something different?
thanks
Alex
