### ISSUE TITLE
Move report generation to AWS Lambda

### ISSUE THREAD

**Issue by NomisNostab** [NomisNostab/Topo#125]

**Comment by waynethompson** [comment]
Curious, why not Azure functions?
Seems a better development experience for C# and can get NFP credits.

**Comment by NomisNostab** [comment]
Wayne,
The main reason I didn't go Azure Functions was that Terrain is running out of AWS.
So, at some time in the future the report generation function could be moved to the Terrain account so I don't have to pay for it :-)
Just hoping.

**Comment by waynethompson** [comment]
oh yeah that makes sense.

**Comment by NomisNostab** [comment]
Report generation for the Blazor version of Topo is complete. The original version of Topo will not get the change.
