### ISSUE TITLE
Transpose the OAS reports

### ISSUE THREAD

**Issue by acsand** [NomisNostab/Topo#139]
Can the OAS reports be transposed so the "I statements" run vertical down the page and the member names horizontally across the page? I'm finding when printing off the reports for use by the section leaders that the "I statements" are really hard to read. By transposing the reports it can improve readability when in hard copy.

**Comment by acsand** [comment]
I just realised this request was already raised in #137

**Comment by marklim** [comment]
@acsand I've actually made the code changes. Just waiting for Simon to review and merge them

**Comment by NomisNostab** [comment]
Done as part of #137 , which has been released.
Will close
