### ISSUE TITLE
Wallchart report not updating

### ISSUE THREAD

**Issue by acsand** [NomisNostab/Topo#140]
Hey team, it appears that the Wallchart report isn't updating. I had one Scout complete a "Lead" tonight, but it's not in the Wallchart report, and several Scouts achieve OAS stages that aren't showing up either.

**Comment by richxrich** [comment]
You have to logout and log back in for TOPO to download the data again after you have updated Terrain. Your browser also might be cache-ing it, so perhaps close all browser windows and reopen to be sure.

**Comment by acsand** [comment]
Ignore the above. Restarted the browser and fixed the report. Also the Approvals report is now enabled. Thanks!

**Comment by acsand** [comment]
Following advice from @richxrich and resolved issue.
