### ISSUE TITLE
Removing data from Members List report

### ISSUE THREAD

**Issue by acsand** [NomisNostab/Topo#142]
Hey Topo dev team...I've had a long think about this, and in the interests of minimising the risk of violating member privacy I want to request that the DoB and Member Number fields be removed from the Members List report. General privacy principles are that you don't want to expose full name and DoB - particularly when this data can be exported out of Topo after which there is no controls over the data. 
Member Number is probably less of a risk, as the only value (I can see in it) is in accessing Scout systems, but has the potential for being used maliciously in the hands of someone with sinister intentions.

**Comment by NomisNostab** [comment]
Hi Andrew,
No problems in removing the DOB from the Members List report and keeping the Age in Years and Months.
Will remove the member number from the attendance list, sign-in sheet, patrol list and patrol sheets. Would like to keep on the member list.
