### ISSUE TITLE
Milestone Participation - Inconsistency between Attendance Report and Wall-Chart/Milestone Reports?

### ISSUE THREAD

**Issue by alexmckenzie1** [NomisNostab/Topo#144]
hi Simon,

If I run the attendance report for 1st Ivanhoe venturers, I can see that Heather Bateman has 42 participates across a range of activities however when I go to the Wall Chart or Milestone reports she is only credited with Milestone 1 (24 activities in total) + 3 activities in Milestone 2.     Is there a reason for this difference please since all the activities appear to be concluded as per the report?

[Attendance_Venturer_Unit.xlsx](https://github.com/NomisNostab/Topo/files/9993188/Attendance_Venturer_Unit.xlsx)
[Wallchart_Report_Venturer_Unit.pdf](https://github.com/NomisNostab/Topo/files/9993191/Wallchart_Report_Venturer_Unit.pdf)

**Comment by NomisNostab** [comment]
Hi Alex,
Interesting.
The Attendance report goes through each event in the date range and uses the attendance recorded against the event.
The Wall Chart and Milestone reports use the data from the Group Life page for the unit. So what has been recorded as PALs.
I wonder if she is missing any participates? Note that extra assists and leads do not carry through to the next milestone.
Also and participates when linking don't get counted.
I will have a look at some of our scouts to see if the same thing is happening.

**Comment by alexmckenzie1** [comment]
Thanks Simon - I tried digging deeper but I am limited in what data I can access.  I matched the activities from Heather's Milestone 1 review (since you can see them when completed) and then checked some of the earlier ones to make sure that she had the participate marked.  From a straight logic point of view I would expect the first 6 participates that a person does in a particular category would count towards Milestone 1 but that does not seem to be happening.  Updated data file attached showing my checks.
[Attendance_Venturer_Unit - Heather Bateman.xlsx](https://github.com/NomisNostab/Topo/files/9998022/Attendance_Venturer_Unit.-.Heather.Bateman.xlsx)

**Comment by richxrich** [comment]
Hi Alex,

Has Heather completed her review on her profile for the milestone, submitted it, and has it been (double) approved by unit council / leaders?

Rich

**Comment by alexmckenzie1** [comment]
hi Rich,

It is shown as awarded on 26th October 2022.

![image](https://user-images.githubusercontent.com/109391101/201541366-b41dab42-23a1-43ad-a353-4be770398ffe.png)

Even if this was not the case I would have expected the cumulative participates would still count towards the other milestones (noting that Leads/Assists do not)?

thanks Alex

**Comment by richxrich** [comment]
Hi Alex,

Does the milestone 2 have the leads? I know I had problems if I didn't select participate and set the Scout as lead it didn't show up.

Rich

**Comment by alexmckenzie1** [comment]
This is what I can see on her profile for Milestone 2.  I don't know what the Draft means?
![image](https://user-images.githubusercontent.com/109391101/201541907-d34c1b39-5cbd-4c5d-86df-a4b39aa8dd2e.png)

**Comment by richxrich** [comment]
Hi Alex,

They need to have the review done for them, submitted and approved. They then will count.

Rich

**Comment by alexmckenzie1** [comment]
If I look at one of them as an example (Shrine of Remembrance which is showing as Draft) the review has been completed?

![image](https://user-images.githubusercontent.com/109391101/201542143-5c37a3bd-7632-4195-88a3-5c1b87871363.png)

And Heather has added a comment:

![image](https://user-images.githubusercontent.com/109391101/201542194-c1c3dedf-04a3-408c-bee9-67cc710e300c.png)

And these are leads/assists which are different to the participates anyway?

**Comment by richxrich** [comment]
Be careful putting real names here this is a public system. Have they been approved twice?

**Comment by NomisNostab** [comment]
Alex,
I you can use the original downloaded Topo.
Start Topo, run the Attendance report and then run the wall chart report.
Stop Topo.
In the Topo folder there will be a file nlog-Topo-all.log email that to me. PM me on farcebook if you need my address.

Simon.

**Comment by alexmckenzie1** [comment]
Pinged you on Messenger for email.  thanks Alex

**Comment by NomisNostab** [comment]
I will change the Attendance report to show P/A/L instead of a 0/1 against events.

**Comment by alexmckenzie1** [comment]
That would be great - thanks Simon.  I assume the total lines would still show a numerical count (being the sum of P/A/L)

**Comment by NomisNostab** [comment]
Yes, they would

**Comment by NomisNostab** [comment]
Included in v1.35
