### ISSUE TITLE
Milestone report- don't report skipped Milestones

### ISSUE THREAD

**Issue by marklim** [NomisNostab/Topo#18]
As a user of the Milestone report, when a member has skipped a Milestone, I don't want this displayed as being achieved (marked in Green). Instead, I want to see skipped milestones for a member greyed out

**Comment by marklim** [comment]
Raised https://github.com/NomisNostab/Topo/pull/19 for code fix
Test evidence:
![image](https://user-images.githubusercontent.com/28877817/164649423-2ea627f7-d4f9-43af-a442-2499ffb992b5.png)

**Comment by NomisNostab** [comment]
Hi Mark,
I don't have any skipped milestones in my group.
Could you run a Milestone and Wallchart report to see how they are handled?
I think the milestone one should be fine as I am only showing active milestones, but the wallchart might not be quite right.
