### ISSUE TITLE
Different views between leaders and unit council

### ISSUE THREAD

**Issue by allovesstairs** [NomisNostab/Topo#88]
Hi,
Our venturer unit council has noticed that in the wallsheet report that leaders and unit council have different data generated for the reports: the leader can access everyone's SIAs, but unit council can only see their own (see attached screenshots, these were taken at the same time).
Is it possible for unit council to be able to access everyone's SIAs (we can do it through terrain in unit life, but not through Topo)? This would be really helpful because our unit council manages all badge reports, not our leaders.
Thanks
![leader view wallchart](https://user-images.githubusercontent.com/107172358/172783437-a46428f1-b7a4-4e8a-9939-2758970f7d16.png)
![unit council view wallchart](https://user-images.githubusercontent.com/107172358/172783454-e60fa4a8-fdb8-4819-b69d-89442aba40be.png)

**Comment by allovesstairs** [comment]
Just found that the same issue presents when trying to generate SIA and Logbook reports for anyone other than myself - it just generates a blank page with the unit name at the top. (however this is probably due to a lack of access on Terrain so not much we can do there anyway).

**Comment by NomisNostab** [comment]
Hi,

SIA are a bit of a pain.
The Group/Unit life pages just show an overview of what has been achieved, the number of project completed, the areas covered and in progress. But I can't get the details of how many projects in each area from that data, I have to impersonate each user to see their data. This is why is is working for leaders and not youth members as leaders can impersonate youth via the manage achievement pathways link.
I don't think there is any way around this, other than the leaders getting the report for the unit council.
Simon
